### PR TITLE
evpn-mh tutorial added

### PR DESCRIPTION
**Pull request by aaakpinar**
EVPN multi-homing tutorial (draft) added

### CODE REVIEW

**Comment by aaakpinar** [comment]
> Hi @aaakpinar I should be able to start a review this week. First thing I'd ask you to put the lab files to a repo I created -- https://github.com/srl-labs/srl-l3evpn-lab/tree/main
> 
> For l2evpn I had the files in learn.srlinux.dev repo, but this proved to be an inconvenient way of hosting lab files.
> 
> And same for the diagram - it should be moved to a lab repo

Okay @hellt will do, but why is the name l3evpn? There's no l3 evpn in this one. Could you create something like 'srl-evpn-mh-lab' for this one? 

It would make more sense if we get hackathon's 'srl-generic-lab' as 'srl-l3evpn-lab' here.

**Comment by hellt** [comment]
@aaakpinar my bad, I will rename it to srl-evpn-mh-lab

**Comment by hellt** [comment]
renaming done

**Comment by aaakpinar** [comment]
> renaming done

I was using the below method to show the lab files (took it from the l2evpn tutorial). 

```yaml
--8<-- "labs/evpn-mh/evpn-mh.clab.yml"
```

Since the lab files are in another repo now, would it work if I use the full URL there? 

```yaml
--8<-- "https://github.com/srl-labs/srl-evpn-mh-lab/evpn-mh.clab.yml"
```

It's not something that automatically works in GitHub so I'm not sure.

**Comment by hellt** [comment]
@aaakpinar you have to use raw.github links for that

**Comment by aaakpinar** [comment]
Just pushed a draft. Ready for a review.

**Comment by hellt** [comment]
resubmitted in #100

**Pull request closed without merging**
